name: oauth_flutter
description: "A complete OAuth2 solution for Flutter apps. Handles auth, token storage, and token refresh."
version: 0.0.8
homepage: https://github.com/IO-Design-Team/oauth_flutter

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.1.0
  fresh_dio: ^0.4.3
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  jwt_decoder: ^2.0.1
  pkce: ^1.1.0+1
  crypto: ^3.0.6

dev_dependencies:
  rexios_lints: ^10.1.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
